### ISSUE TITLE
mamonedeffrbktoldmmon.hdf5 model?

### ISSUE THREAD

**Issue by xugaoxiang** [mamonraab/Real-Time-Violence-Detection-in-Video-#3]
Hi, where can I get the model mamonedeffrbktoldmmon.hdf5? thanks.

**Comment by yasergsi** [comment]
I think that is a mistake by the Author. You can use this one instead: https://drive.google.com/file/d/11IN2npH3i8PhzECNMcxfIQNFWPROr5gt/view?usp=sharing
